baseURL = "https://cosmotek.github.io"
languageCode = "en-us"
title = "cosmotek"
theme = "showfolio"

[params]
  name = "Seth Moeckel"
  description = "Fullstack Software Engineer"
  author = "Seth Moeckel"
  authorEmail = "seth.moeckel@gmail.com"
  authorImage = "/photo.png"
  autoDarkMode = true

  copyright = "Copyright © 2021 - Seth Moeckel · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Seth"
  tagline = "Fullstack Software Engineer"
  description = "I create "
  contact = "mailto:seth.moeckel@gmail.com"

[params.homepage.codepen]
  username = "apvarun"
  pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.resume]
  skills = ["Visual Design", "Product Development"]

[[params.homepage.resume.work]]
  name = "Google"
  role = "Product Engineer"
  duration = "Nov 2019 - Apr 2021"

[[params.homepage.resume.work]]
  name = "Amazon"
  role = "Sr. UX Designer"
  duration = "Jan 2016 - Oct 2019"

[[params.homepage.resume.courses]]
  name = "Design Principles"
  provider = "UX Academy"
  duration = "Nov 2019 - Jan 2020"

[params.homepage.social]
  linkedin = "https://www.linkedin.com/in/seth-m-b8773b123/"
  github = "https://github.com/cosmotek"
  resume = "https://docs.google.com/document/d/121mt-BFw6SAP9RMiQ3hFMm-R_MNIDw-Us4UcDI_3xUU/edit?usp=sharing"
  phone = "tel:740-877-2320"
  email = "mailto:seth.moeckel@gmail.com"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
