baseURL = "https://cosmotek.github.io"
languageCode = "en-us"
title = "cosmotek"
theme = "showfolio"

[params]
  name = "Seth Moeckel"
  description = "Seth Moeckel, Fullstack Software Engineer 👋"
  author = "Seth Moeckel"
  authorEmail = "seth.moeckel@gmail.com"
  authorImage = "/photo.png"
  autoDarkMode = false

  copyright = "Copyright © 2021 - Seth Moeckel · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Seth"
  tagline = "I build cool sh*t"
  description = "I'm a software engineer who's passionate about building innovative & original digital experiences."
  contact = "mailto:seth.moeckel@gmail.com"

[[params.homepage.projects]]
  title = "Dropship"
  description = "P2P videogame downloader with remote controls and a reverse engineered Stream integration"
  url = "https://github.com/cosmotek/dropship"
  image = "/dropship.png"

[[params.homepage.projects]]
  title = "iVueit Mobile App"
  description = "I was one of two core engineers behind the iVueit v2 mobile app. We built out a new Flutter app, Go APIs and custom infrastructure"
  url = "https://ivueit.com/"
  image = "/ivueit.png"

[[params.homepage.projects]]
  title = "API Commons"
  description = "I maintain a collection of API libraries for everything from authentication to geolocation (preview is of a dev sms/email debug server)"
  url = "https://github.com/cosmotek/api-commons"
  image = "/api-commons.png"

[[params.homepage.projects]]
  title = "Flutter QR Code Generator"
  description = "Just a simple Flutter-web interface for generating custom QR codes"
  url = "https://github.com/cosmotek/qr_code_gen"
  image = "/qr_code_gen.png"

[[params.homepage.projects]]
  title = "LedFS"
  description = "I built an embedded application that allows any application to drive RGB LEDs on a Raspberry Pi using only JSON files"
  url = "https://github.com/cosmotek/ledfs"
  image = "/ledfs.png"

[params.homepage.social]
  linkedin = "https://www.linkedin.com/in/seth-m-b8773b123/"
  github = "https://github.com/cosmotek"
  resume = "https://docs.google.com/document/d/121mt-BFw6SAP9RMiQ3hFMm-R_MNIDw-Us4UcDI_3xUU/edit?usp=sharing"
  phone = "tel:740-877-2320"
  email = "mailto:seth.moeckel@gmail.com"

[build]
  writeStats = true

[markup]
  [markup.highlight]
    style = "dracula"
