baseURL = "https://cosmotek.github.io"
languageCode = "en-us"
title = "The personal blog of Seth Moeckel"

[[params.mainMenu]]
    link = "/posts"
    text = "writing"

[[params.mainMenu]]
    link = "/work"
    text = "portfolio"

[[params.mainMenu]]
    link = "/projects"
    text = "side projects"

[[params.mainMenu]]
    link = "/about"
    text = "who is seth moeckel?"
