baseURL = "http://example.org/"
languageCode = "en-us"
title = "The personal blog of Seth Moeckel"

[[params.mainMenu]]
    link = "/posts"
    text = "writing"

[[params.mainMenu]]
    link = "/about"
    text = "who is seth moeckel?"
